name: CI - Build and Upload WAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: mi-aplicacion-web   # Nombre base para el WAR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR with Maven
        run: mvn -B clean package -DskipTests=true

      - name: Get WAR name
        id: get-war-name
        run: |
          # Busca el primer archivo .war dentro de target/
          war=$(ls target/*.war | head -n 1)
          echo "WAR encontrado: $war"
          # Extrae solo el nombre de archivo (sin ruta)
          war_name=$(basename "$war")
          # Exporta el nombre como output
          echo "war_name=$war_name" >> $GITHUB_OUTPUT

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: ${{ env.PROJECT_NAME }}-war
          path: target/${{ steps.get-war-name.outputs.war_name }}
          retention-days: 7

